#ifndef GUARD_CONSTANTS_ATHENS_OLD_MAN_H
#define GUARD_CONSTANTS_ATHENS_OLD_MAN_H

#define ATHENS_MAN_BARD           0
#define ATHENS_MAN_HIPSTER        1
#define ATHENS_MAN_TRADER         2
#define ATHENS_MAN_STORYTELLER    3
#define ATHENS_MAN_GIDDY          4
#define ATHENS_MAN_UNUSED1        5
#define ATHENS_MAN_UNUSED2        6

#endif // GUARD_CONSTANTS_ATHENS_OLD_MAN_H
