gText_Birch_Welcome::
	.string "Hello my child! I am your father, Zeus. \p"
	.string "It's finally time for you to move to \n"
	.string "the Greek mainland and begin your \l"
	.string "own adventure.\p"
	.string"$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"	
	.string"$"

gText_Birch_MainSpeech::
	.string "They are creatures you must learn \n"
	.string "to befriend and control if you want to \l"
	.string "hold any sway in this world.\p"
	.string "Throughout your odyssey you will \n"
	.string "encounter fellow Gods, people and \l"
	.string "POKéMON of all kinds. \p"
	.string "If you manage to find and defeat the \n"
	.string "8 temple leaders, you can make your \l"
	.string "way to Mt. Olympus to challenge the \l"
	.string "4 strongest Olympians, including me! \p"
	.string "But before setting off, you should \n"
	.string "really freshen up your appearance. \p"
	.string "I won't have my child looking so ragged! \p"
	.string "$"

gText_Birch_AndYouAre::
	.string "How would you like to look?$"

gText_Birch_BoyOrGirl::
	.string "Which appearance?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "And, er, remind me of you name again?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}, did I hear that right?$"

gText_Birch_YourePlayer::
	.string "Ah, of course it's {PLAYER}{KUN}. Now, I \n"
	.string "have arranged for a carriage to drop \l"
	.string "you off in Archi Town. \p"
	.string "There you will meet Athena, my daughter, \n"
	.string "she will teach you the ropes. \p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Who knows, if you prove yourself worthy \n"
	.string "we may meet again atop Mt. Olympus! \p" 
	.string "$"
