Text_BootUpPC:
	.string "{PLAYER} reached into The Sack.$"

gText_WhichPCShouldBeAccessed::
	.string "Which pocket should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed POKéMON storage pocket.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage Pocket opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s Pocket.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"
